version: '3.8'
services:
  app:
    container_name: my-nestjs-app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/mydb
    depends_on:
      - db

  db:
    container_name: my-postgres-db
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
volumes:
  pgdata: